In [1]:
import torch
import numpy as np

# 1. Illustrating the functions for Reshaping, Viewing, Stacking, Squeezing, and Unsqueezing of tensors

In [2]:
# Create a tensor
tensor = torch.arange(0, 12).reshape(3, 4)
print(f"Original Tensor:\n{tensor}\n")

# Reshape: Change shape to (2, 6)
reshaped_tensor = tensor.view(2, 6)
print(f"Reshaped Tensor:\n{reshaped_tensor}\n")

# Stacking: Stack tensors along a new dimension (dim=0 for stacking along rows)
tensor1 = torch.tensor([1, 2, 3])
tensor2 = torch.tensor([4, 5, 6])
stacked_tensor = torch.stack([tensor1, tensor2], dim=0)
print(f"Stacked Tensor (dim=0):\n{stacked_tensor}\n")

# Squeeze: Remove dimensions with size 1
squeezed_tensor = tensor1.unsqueeze(0)  # Adds a dimension
print(f"Tensor after unsqueeze:\n{squeezed_tensor}\n")
squeezed_tensor = squeezed_tensor.squeeze()  # Removes the added dimension
print(f"Tensor after squeeze:\n{squeezed_tensor}\n")

# Unsqueeze: Add a new dimension (e.g., at the 0th axis)
unsqueezed_tensor = tensor1.unsqueeze(0)
print(f"Tensor after unsqueeze:\n{unsqueezed_tensor}\n")

Original Tensor:
tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])

Reshaped Tensor:
tensor([[ 0,  1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10, 11]])

Stacked Tensor (dim=0):
tensor([[1, 2, 3],
        [4, 5, 6]])

Tensor after unsqueeze:
tensor([[1, 2, 3]])

Tensor after squeeze:
tensor([1, 2, 3])

Tensor after unsqueeze:
tensor([[1, 2, 3]])



# 2. Illustrate the use of torch.permute()

In [3]:
# Permute the tensor to rearrange its dimensions
tensor = torch.randn(2, 3, 4)
permuted_tensor = tensor.permute(2, 0, 1)  # Changing the dimension order
print(f"Permuted Tensor (shape {tensor.shape} -> {permuted_tensor.shape}):\n{permuted_tensor}\n")

Permuted Tensor (shape torch.Size([2, 3, 4]) -> torch.Size([4, 2, 3])):
tensor([[[ 4.1651e-01, -4.2805e-01,  4.4748e-01],
         [-5.7497e-04,  1.7816e+00, -8.9786e-01]],

        [[-4.1270e-01, -2.4909e-01,  1.9518e-01],
         [ 1.0884e+00,  1.6772e+00,  6.2162e-01]],

        [[-6.7425e-01,  2.2423e-01, -7.0681e-01],
         [-9.4926e-01,  7.5425e-01,  8.1327e-01]],

        [[ 1.4910e+00, -1.9471e+00,  5.2051e-02],
         [-2.1864e+00, -9.7201e-01, -7.8740e-01]]])



# 3. Illustrating indexing in tensors

In [4]:
# Indexing like NumPy for tensors
tensor = torch.randn(4, 5)
print(f"Original Tensor:\n{tensor}\n")

# Indexing with integers
print(f"Element at (2, 3): {tensor[2, 3]}")

# Slicing: Selecting rows and columns
print(f"First row:\n{tensor[0]}")
print(f"First column:\n{tensor[:, 0]}")

Original Tensor:
tensor([[ 0.6128,  0.5297,  1.3399, -0.3043, -0.5171],
        [ 0.0146, -0.9525,  0.1967, -0.2394,  1.6823],
        [ 0.0276,  0.0894, -0.6846,  0.4375,  1.3078],
        [ 1.3534,  0.3043, -1.4005, -1.1104, -1.8180]])

Element at (2, 3): 0.4374532699584961
First row:
tensor([ 0.6128,  0.5297,  1.3399, -0.3043, -0.5171])
First column:
tensor([0.6128, 0.0146, 0.0276, 1.3534])


# 4. Convert NumPy arrays to tensors and back to NumPy arrays

In [5]:
# NumPy array
np_array = np.array([[1, 2, 3], [4, 5, 6]])
print(f"NumPy Array:\n{np_array}\n")

# Convert to tensor
tensor_from_np = torch.from_numpy(np_array)
print(f"Tensor from NumPy array:\n{tensor_from_np}\n")

# Convert back to NumPy array
np_from_tensor = tensor_from_np.numpy()
print(f"Back to NumPy Array:\n{np_from_tensor}\n")

NumPy Array:
[[1 2 3]
 [4 5 6]]

Tensor from NumPy array:
tensor([[1, 2, 3],
        [4, 5, 6]])

Back to NumPy Array:
[[1 2 3]
 [4 5 6]]



# 5. Create a random tensor with shape (7, 7)

In [6]:
random_tensor_7x7 = torch.randn(7, 7)
print(f"Random Tensor (7x7):\n{random_tensor_7x7}\n")

Random Tensor (7x7):
tensor([[ 2.2529,  0.5792,  0.2023,  0.2131,  0.0702,  1.2424,  0.5509],
        [-1.2857, -1.7647,  0.1428, -1.8264, -1.3980,  2.5269, -0.3494],
        [-1.2335,  0.8831, -1.0873,  0.3449, -0.1455,  0.2494,  1.2583],
        [ 1.2268,  0.1809,  0.3914,  0.1032,  0.3926, -1.5105,  0.0091],
        [-0.5754,  0.7066, -1.0438, -0.4915, -0.7921, -0.0456,  1.1955],
        [ 1.3387,  1.4668,  1.1827,  0.1575, -0.8039, -1.2712,  0.1506],
        [ 0.4267, -0.7522,  0.0394,  0.2061,  1.2384,  1.2230,  0.8108]])



# 6. Matrix multiplication (hint: transpose the second tensor)

In [7]:
random_tensor_1x7 = torch.randn(1, 7)
print(f"Tensor (1x7):\n{random_tensor_1x7}\n")

# Matrix multiplication (transposing the second tensor)
result = torch.matmul(random_tensor_7x7, random_tensor_1x7.t())
print(f"Matrix Multiplication Result:\n{result}\n")

Tensor (1x7):
tensor([[ 1.2972,  2.6236, -0.7863,  1.2377,  0.0326,  1.1760,  0.9775]])

Matrix Multiplication Result:
tensor([[ 6.5489],
        [-6.0860],
        [ 3.5174],
        [ 0.1311],
        [ 2.4093],
        [ 3.4760],
        [ 1.0755]])



# 7. Create two random tensors of shape (2, 3) and send them to the GPU (if available)

In [8]:
device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
tensor_a = torch.randn(2, 3).to(device)
tensor_b = torch.randn(2, 3).to(device)
print(f"Tensor A (GPU):\n{tensor_a}\n")
print(f"Tensor B (GPU):\n{tensor_b}\n")

Tensor A (GPU):
tensor([[-0.8544, -1.0040, -0.5155],
        [-0.3867, -0.3859,  0.2907]])

Tensor B (GPU):
tensor([[-1.4701, -0.8540,  0.4091],
        [ 1.0798,  0.2994,  0.1801]])



# 8. Matrix multiplication on the tensors (adjust shapes if needed)

In [9]:
result_gpu = torch.matmul(tensor_a, tensor_b.t())
print(f"Matrix Multiplication Result on GPU:\n{result_gpu}\n")

Matrix Multiplication Result on GPU:
tensor([[ 1.9026, -1.3160],
        [ 1.0169, -0.4807]])



# 9. Find the maximum and minimum values of the output of step 7

In [10]:
max_val = result_gpu.max()
min_val = result_gpu.min()
print(f"Max value: {max_val}")
print(f"Min value: {min_val}")

Max value: 1.902587652206421
Min value: -1.316036581993103


# 10. Find the maximum and minimum index values of the output of step 7

In [11]:
max_idx = result_gpu.argmax()
min_idx = result_gpu.argmin()
print(f"Max Index: {max_idx}")
print(f"Min Index: {min_idx}")

Max Index: 0
Min Index: 1


# 11. Create a random tensor with shape (1, 1, 1, 10) and remove 1-dimensional entries

In [12]:
torch.manual_seed(7)  # Set seed for reproducibility
tensor_1x1x1x10 = torch.randn(1, 1, 1, 10)
print(f"Tensor with shape (1, 1, 1, 10):\n{tensor_1x1x1x10}\n")
tensor_10 = tensor_1x1x1x10.squeeze()
print(f"Tensor after squeeze (shape (10)):\n{tensor_10}\n")

Tensor with shape (1, 1, 1, 10):
tensor([[[[-0.1468,  0.7861,  0.9468, -1.1143,  1.6908, -0.8948, -0.3556,
            1.2324,  0.1382, -1.6822]]]])

Tensor after squeeze (shape (10)):
tensor([-0.1468,  0.7861,  0.9468, -1.1143,  1.6908, -0.8948, -0.3556,  1.2324,
         0.1382, -1.6822])

