In [1]:
import torch 
torch.__version__ 

'2.5.1+cpu'

# Introduction to tensors

##  • Creating Tensors

In [2]:
# Scalar 
scalar = torch.tensor(7) 
scalar

tensor(7)

In [3]:
# Get the Python number within a tensor (only works with one-element tensors) 
scalar.item()

7

In [4]:
# Vector 
vector = torch.tensor([7, 7]) 
vector 

tensor([7, 7])

In [5]:
# Matrix 
MATRIX = torch.tensor([[7, 8],  
[9, 10]]) 
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [6]:
MATRIX.shape

torch.Size([2, 2])

In [7]:
# Tensor 
TENSOR = torch.tensor([[[1, 2, 3], 
[3, 6, 9], 
[2, 4, 5]]]) 
TENSOR

tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 5]]])

In [8]:
# Check number of dimensions for TENSOR 
TENSOR.ndim

3

## • Random Tensors

In [9]:
# Create a random tensor of size (3, 4) 
random_tensor = torch.rand(size=(3, 4)) 
random_tensor, random_tensor.dtype 

(tensor([[0.8383, 0.5460, 0.7696, 0.6425],
         [0.2521, 0.6752, 0.0970, 0.9256],
         [0.9396, 0.2222, 0.6581, 0.7591]]),
 torch.float32)

In [10]:
# Create a random tensor of size (224, 224, 3) 
random_image_size_tensor = torch.rand(size=(224, 224, 3)) 
random_image_size_tensor.shape, random_image_size_tensor.ndim 

(torch.Size([224, 224, 3]), 3)

## • Zeros and ones

In [11]:
# Create a tensor of all zeros 
zeros = torch.zeros(size=(3, 4)) 
zeros, zeros.dtype

(tensor([[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]),
 torch.float32)

In [12]:
# Create a tensor of all ones 
ones = torch.ones(size=(3, 4)) 
ones, ones.dtype

(tensor([[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]),
 torch.float32)

## • Range in Tensors

In [13]:
# Use torch.arange(), torch.range() is deprecated  
zero_to_ten_deprecated = torch.range(0, 10) # Note: this may return an error in the future 
# Create a range of values 0 to 10 
zero_to_ten = torch.arange(start=0, end=10, step=1) 
zero_to_ten

C:\Users\YASH SRIVASTAVA\AppData\Local\Temp\ipykernel_55084\1962218769.py:2: UserWarning: torch.range is deprecated and will be removed in a future release because its behavior is inconsistent with Python's range builtin. Instead, use torch.arange, which produces values in [start, end).
  zero_to_ten_deprecated = torch.range(0, 10) # Note: this may return an error in the future


tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [14]:
# Can also create a tensor of zeros similar to another tensor 
ten_zeros = torch.zeros_like(input=zero_to_ten) # will have same shape 
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

## • Tensor Data Type

In [15]:
 
# Create a tensor 
some_tensor = torch.rand(3, 4) 
 
# Find out details about it 
print(some_tensor) 
print(f"Shape of tensor: {some_tensor.shape}") 
print(f"Datatype of tensor: {some_tensor.dtype}") 
print(f"Device tensor is stored on: {some_tensor.device}") # will default to CPU

tensor([[0.9833, 0.2081, 0.6234, 0.8104],
        [0.2974, 0.0852, 0.2029, 0.7024],
        [0.7829, 0.1908, 0.0543, 0.3999]])
Shape of tensor: torch.Size([3, 4])
Datatype of tensor: torch.float32
Device tensor is stored on: cpu


# Manipulating Tensors (Tensor Operations)

## • Basic Operations

In [16]:
# Create a tensor of values and add a number to it 
tensor = torch.tensor([1, 2, 3]) 
tensor + 10 

tensor([11, 12, 13])

In [17]:
# Multiply it by 10 
tensor * 10

tensor([10, 20, 30])

Notice how the tensor values above didn't end up being tensor([110, 120, 130]), this is because the values inside the tensor don't change unless 
they're reassigned. 

In [18]:
# Tensors don't change unless reassigned 
tensor 

tensor([1, 2, 3])

In [19]:
# Let's subtract a number and this time we'll reassign the tensor variable. 
# Subtract and reassign 
tensor = tensor - 10 
tensor 

tensor([-9, -8, -7])

In [20]:
# Add and reassign 
tensor = tensor + 10 
tensor

tensor([1, 2, 3])

In [21]:
# PyTorch also has a bunch of built-in functions like torch.mul() (short for multiplcation) and torch.add() to perform basic operations. 
# Can also use torch functions 
torch.multiply(tensor, 10) 

tensor([10, 20, 30])

In [22]:
# Original tensor is still unchanged  
tensor

tensor([1, 2, 3])

In [23]:
# Element-wise multiplication (each element multiplies its equivalent, index 0->0, 1->1, 2->2) 
print(tensor, "*", tensor) 
print("Equals:", tensor * tensor)

tensor([1, 2, 3]) * tensor([1, 2, 3])
Equals: tensor([1, 4, 9])


## • Matrix Multiplication

In [24]:
tensor = torch.tensor([1, 2, 3]) 
tensor.shape

torch.Size([3])

In [25]:
# Element-wise matrix multiplication 
tensor * tensor

tensor([1, 4, 9])

In [27]:
# Matrix multiplication 
torch.matmul(tensor, tensor)

tensor(14)

In [28]:
# Can also use the "@" symbol for matrix multiplication, though not recommended 
tensor @ tensor

tensor(14)

 The in-built torch.matmul() method is faster than doing matrix multiplication by hand

In [29]:
%%time 
# Matrix multiplication by hand  
# (avoid doing operations with for loops at all cost, they are computationally expensive) 
value = 0 
for i in range(len(tensor)): 
    value += tensor[i] * tensor[i] 
value 

CPU times: total: 0 ns
Wall time: 8 ms


tensor(14)

In [30]:
%%time 
torch.matmul(tensor, tensor)

CPU times: total: 0 ns
Wall time: 1 ms


tensor(14)

# Getting PyTorch to run on the GPU

In [31]:
# You can test if PyTorch has access to a GPU using torch.cuda.is_available(). 
# Check for GPU 
torch.cuda.is_available() 

False

In [32]:
# Let's create a device variable to store what kind of device is available. 
# Set device type 
device = "cuda" if torch.cuda.is_available() else "cpu" 
device 

'cpu'

In [33]:
# Count number of devices 
torch.cuda.device_count()

0

## • Putting tensors (and models) on the GPU 

In [34]:
# Create tensor (default on CPU) 
tensor = torch.tensor([1, 2, 3]) 
# Tensor not on GPU 
print(tensor, tensor.device) 
# Move tensor to GPU (if available) 
tensor_on_gpu = tensor.to(device) 
tensor_on_gpu

tensor([1, 2, 3]) cpu


tensor([1, 2, 3])

## • Moving tensors back to the CPU

In [35]:
# If tensor is on GPU, can't transform it to NumPy (this will error) 
tensor_on_gpu.numpy()

array([1, 2, 3])

In [36]:
# Instead, copy the tensor back to cpu 
tensor_back_on_cpu = tensor_on_gpu.cpu().numpy() 
tensor_back_on_cpu

array([1, 2, 3])